crud_cbv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clientes/', include('exemplo.urls'))
]

exemplo/urls.py
from django.urls import path

from exemplo import views


app_name = 'exemplo'

urlpatterns = [
    path('', views.ClienteList.as_view(), name='list'),
    path('create/', views.ClienteCreate.as_view(), name='create'),
    path('update/<int:pk>/', views.ClienteUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', views.ClienteDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.ClienteDelete.as_view(), name='delete'),
]

exemplo/models.py
from django.db import models


class Cliente(models.Model):
    nome = models.CharField(max_length=30)
    idade = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        return self.nome

exemplo/forms.py
from django import forms

from exemplo.models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

exemplo/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from exemplo.models import Cliente


class ClienteList(ListView):
    model = Cliente
    queryset = Cliente.objects.all()


class ClienteCreate(CreateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('exemplo:list')


class ClienteUpdate(UpdateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('exemplo:list')


class ClienteDetail(DetailView):
    queryset = Cliente.objects.all()


class ClienteDelete(DeleteView):
    queryset = Cliente.objects.all()
    success_url = reverse_lazy('exemplo:list')

templates/exemplo/cliente_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Tem certeza que deseja apagar o cliente <strong>{{ object.nome }}</strong>?
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" value="Sim, tenho certeza">
    <input type="reset" value="Não quero apagar mais" onclick="location.href='{% url 'exemplo:list' %}'">
</form>
</body>
</html>

templates/exemplo/cliente_detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Teste
<input type="submit" value="Voltar para lista" onclick="location.href='{% url 'exemplo:list' %}'">
<br>
Nome: {{ object.nome }}
<br>
Idade: {{ object.idade }}
</body>
</html>

templates/exemplo/cliente_form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Cadastro de Cliente</h1>
<br>
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Salvar">
    <input type="reset" value="Cancelar" onclick="location.href='{% url 'exemplo:list' %}'">
</form>
</body>
</html>

templates/exemplo/cliente_list.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Lista de Clientes</h1>
<input type="submit" value="Criar novo cliente" onclick="location.href='{% url 'exemplo:create' %}'">
<br>
<ul>
    {% for cliente in object_list %}
        <li>{{ cliente.nome }} -
            <a href="{% url 'exemplo:update' pk=cliente.pk %}">Editar</a> -
            <a href="{% url 'exemplo:detail' pk=cliente.pk %}">Detalhes</a> -
            <a href="{% url 'exemplo:delete' pk=cliente.pk %}">Apagar</a>
        </li>
    {% endfor %}
</ul>
</body>
</html>